config/routes.rb
Rails.application.routes.draw do



  root to: 'posts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :posts, only:[:index, :new, :create]

  resources :users

  resources :relationships, only:[:create, :destroy]




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user

  validates :content, presence:true
end

app/models/relationship.rb
class Relationship <ApplicationRecord

  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  has_secure_password

  validates :name, presence:true
  validates :email, presence:true
  validates :password, presence:true

  # フォローしようとしているユーザーが自分自身ではないか検証
  def follow(other_user)
    unless self==other_user
      relationship=self.relationships.find_by(follow_id: other_user.id)
    end
  end

  # フォローがあればアンフォロー
  def unfollow(other_user)
    relationship=self.relationships.find_by(follow_id: other_user.id)
    relationships.destroy if relationship
  end

  # other_userが含まれているかどうか(含まれている場合true、含まれていない場合false)
  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts=Post.all.order(created_at: :desc)
  end

  def new
    @post=Post.new
  end

  def create
    @post=current_user.posts.new(post_params)

    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/ralationships_controller.rb
class RalationshipsController < ApplicationControlle
  before_action :set_user,only[:create, :destroy]

  def create
    following = current_user.follow(user)
    if following.save
      redirect_to user
    else
      redirect_to user
    end
  end

  def destroy
    following = current_user.unfollow(user)
    if following.destroy
      redirect_to user
    else
      redirect_to user
    end
  end

  private

  def set_user
    user = User.find(params[:relationship][:follow_id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user, only:[:create, :destroy]

  def create
    following = current_user.follow(user)
    if following.save
      redirect_to user
    else
      redirect_to user
    end
  end

  def destroy
    following = current_user.unfollow(user)
    if following.destroy
      redirect_to user
    else
      redirect_to user
    end
  end

  private

  def set_user
    user = User.find(params[:relationship][:follow_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user=User.find_by(email: session_params[:email])

    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user=nil
    redirect_to root_path
  end


  private

    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users=User.all
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)

    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user=User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render 'users/_show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'users/_show_follower'
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ralationships_helper.rb
module RalationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id]=user.id
  end

  #現在のユーザー
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  #ログインしているかしていないか判別
  def logged_in?
    !current_user.nil?
  end

  #渡されたユーザーが現在のユーザーならtrue
  def current_user?(user)
    user==current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FollowFunction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if logged_in? %>
            <li><%= link_to '新規投稿', new_post_path, class: 'nav-link' %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li><%= link_to '新規登録', new_user_path, class: 'nav-link' %></li>
            <li><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <% end %>
          <li><%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>



    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>一覧表示</h1>

<%= link_to '新規投稿', new_post_path, class: 'btn btn-primary' %>

<% @posts.each do |post| %>
  <p><%= post.user.name %>:<%= post.content %></p>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= form_for(@post) do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  <%= f.submit '投稿', class: 'btn btn-primary' %>
<% end %>

app/views/relationships/_form_button.html.erb
<% unless current_user?(user) %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<!-- ユーザー一覧表示-->
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <p>
    <%if current_user?(user) %>
      現在のユーザー→<%= link_to user.name, user %>
    <% else %>
      <%= link_to user.name, user %>
    <% end %>
    <% if current_user.admin? && !current_user?(user) %>
      <%= link_to "削除", user, method: :delete, data: {confirm: "ユーザーを削除します。よろしいですか?"} %>
    <% end %>
  </p>
<% end %>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>

<%= form_with model:@user, local:true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '登録', class: 'btn btn-primary' %>
<% end %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>


<%= render 'relationships/form_button', user: @user %>